import React, { useState } from 'react';
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { Report, Finding, Severity } from '../types';
import FindingEditor from '../components/FindingEditor';
import ReportMetadataEditor from '../components/ReportMetadataEditor';
import { SEVERITY_COLORS } from '../constants';
import { generateExecutiveSummary } from '../services/geminiService';
import { NotificationType } from '../components/Notification';

interface ReportDetailProps {
  report: Report;
  onUpdateReport: (updatedReport: Report) => void;
  onBack: () => void;
  notify: (type: NotificationType, message: string) => void;
  templates?: Partial<Finding>[];
}

const ReportDetail: React.FC<ReportDetailProps> = ({ report, onUpdateReport, onBack, notify, templates = [] }) => {
  const [editingFinding, setEditingFinding] = useState<Finding | null>(null);
  const [isEditingReport, setIsEditingReport] = useState(false);
  const [isGeneratingSummary, setIsGeneratingSummary] = useState(false);
  const [summaryExpanded, setSummaryExpanded] = useState(report.executiveSummary ? true : false);

  const handleCreateFinding = () => {
    const newFinding: Finding = {
      id: '', // Will be assigned on save
      title: '',
      severity: Severity.LOW,
      cvssScore: 0,
      description: '',
      remediation: '',
      references: [],
      status: 'Open'
    };
    setEditingFinding(newFinding);
  };

  const handleEditFinding = (finding: Finding) => {
    setEditingFinding(finding);
  };

  const handleSaveFinding = (finding: Finding) => {
    let updatedFindings;
    if (finding.id) {
      // Update existing
      updatedFindings = report.findings.map(f => f.id === finding.id ? finding : f);
      notify('success', 'Finding updated successfully');
    } else {
      // Create new
      finding.id = `find-${Date.now()}`;
      updatedFindings = [...report.findings, finding];
      notify('success', 'New finding added');
    }
    onUpdateReport({ ...report, findings: updatedFindings });
    setEditingFinding(null);
  };

  const handleDeleteFinding = (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    if(confirm('Are you sure you want to delete this finding?')) {
         const updatedFindings = report.findings.filter(f => f.id !== id);
         onUpdateReport({ ...report, findings: updatedFindings });
         notify('info', 'Finding deleted');
    }
  }

  const handleUpdateReportMetadata = (data: Partial<Report>) => {
      onUpdateReport({ ...report, ...data });
      setIsEditingReport(false);
      notify('success', 'Report details updated');
  };

  const handleGenerateSummary = async () => {
    if (report.findings.length === 0) {
        notify('error', 'Add findings before generating a summary.');
        return;
    }

    setIsGeneratingSummary(true);
    try {
        const summary = await generateExecutiveSummary(report.findings);
        if (summary) {
            onUpdateReport({ ...report, executiveSummary: summary });
            setSummaryExpanded(true);
            notify('success', 'Executive Summary generated by AI');
        } else {
            notify('error', 'Failed to generate summary. Please check your API key.');
        }
    } catch (e) {
        console.error(e);
        notify('error', 'An error occurred while communicating with AI.');
    } finally {
        setIsGeneratingSummary(false);
    }
  };

  const handleExportPDF = () => {
    try {
        const doc = new jsPDF();
        
        // --- Cover Page ---
        doc.setFillColor(26, 27, 38); // pwn-dark
        doc.rect(0, 0, 210, 297, 'F');
        
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(32);
        doc.text("Penetration Test Report", 105, 120, { align: "center" });
        
        doc.setFontSize(16);
        doc.setTextColor(122, 162, 247); // pwn-accent
        doc.text(report.name, 105, 135, { align: "center" });
        
        doc.setTextColor(200, 200, 200);
        doc.setFontSize(12);
        doc.text(`Prepared for: ${report.client}`, 105, 150, { align: "center" });
        doc.text(`Date: ${report.date}`, 105, 160, { align: "center" });

        // --- Executive Summary & Overview ---
        doc.addPage();
        doc.setFillColor(255, 255, 255);
        doc.rect(0, 0, 210, 297, 'F');
        doc.setTextColor(0, 0, 0);

        doc.setFontSize(20);
        doc.text("Executive Summary", 14, 20);
        
        let yPos = 30;
        doc.setFontSize(11);
        doc.setTextColor(60, 60, 60);

        if (report.executiveSummary) {
            // Simple markdown cleaning
            const cleanSummary = report.executiveSummary.replace(/##/g, '').replace(/\*\*/g, '').replace(/- /g, '• ');
            const splitSummary = doc.splitTextToSize(cleanSummary, 180);
            doc.text(splitSummary, 14, yPos);
            yPos += splitSummary.length * 6 + 10;
        } else {
            doc.text("No executive summary available.", 14, yPos);
            yPos += 20;
        }

        doc.setFontSize(16);
        doc.setTextColor(0, 0, 0);
        doc.text("Findings Overview", 14, yPos);
        yPos += 10;

        const tableBody = report.findings.map(f => [
            f.title, 
            f.severity, 
            f.cveId || '-', 
            f.cvssScore.toString(), 
            f.status
        ]);

        autoTable(doc, {
            startY: yPos,
            head: [['Vulnerability', 'Severity', 'CVE', 'CVSS', 'Status']],
            body: tableBody,
            headStyles: { fillColor: [59, 130, 246], textColor: 255 },
            styles: { fontSize: 10, cellPadding: 3 },
            columnStyles: {
                0: { cellWidth: 80 },
                1: { cellWidth: 25 },
                2: { cellWidth: 35 },
                3: { cellWidth: 20 },
                4: { cellWidth: 25 }
            }
        });

        // --- Detailed Findings (The Briefing) ---
        
        // Sort findings for the report
        const severityOrder = {
             [Severity.CRITICAL]: 0,
             [Severity.HIGH]: 1,
             [Severity.MEDIUM]: 2,
             [Severity.LOW]: 3,
             [Severity.INFO]: 4
        };
        const sortedFindings = [...report.findings].sort((a, b) => severityOrder[a.severity] - severityOrder[b.severity]);

        sortedFindings.forEach((finding, index) => {
            doc.addPage();
            let y = 20;

            // Title
            doc.setFontSize(18);
            doc.setTextColor(0, 0, 0);
            doc.text(`${index + 1}. ${finding.title}`, 14, y);
            y += 10;

            // Metadata Box
            doc.setFillColor(245, 247, 250);
            doc.setDrawColor(200, 200, 200);
            doc.rect(14, y, 182, 25, 'FD');
            
            doc.setFontSize(10);
            doc.setTextColor(80, 80, 80);
            
            doc.text("Severity:", 20, y + 8);
            doc.setFont(undefined, 'bold');
            doc.setTextColor(
                finding.severity === Severity.CRITICAL ? 220 : 0, 
                finding.severity === Severity.HIGH ? 100 : 0, 
                0
            );
            doc.text(finding.severity, 40, y + 8);
            
            doc.setFont(undefined, 'normal');
            doc.setTextColor(80, 80, 80);
            doc.text("CVSS Score:", 80, y + 8);
            doc.setFont(undefined, 'bold');
            doc.text(finding.cvssScore.toString(), 105, y + 8);

            doc.setFont(undefined, 'normal');
            doc.text("CVE ID:", 140, y + 8);
            doc.setFont(undefined, 'bold');
            doc.text(finding.cveId || 'N/A', 160, y + 8);

            doc.setFont(undefined, 'normal');
            doc.text("Status:", 20, y + 18);
            doc.text(finding.status, 40, y + 18);

            doc.text("OWASP:", 80, y + 18);
            doc.text(finding.owaspId ? finding.owaspId.split(':')[0] : 'N/A', 105, y + 18);

            y += 35;

            // Description
            doc.setFontSize(14);
            doc.setTextColor(0, 0, 0);
            doc.text("Description", 14, y);
            y += 7;
            doc.setFontSize(11);
            doc.setTextColor(60, 60, 60);
            const descLines = doc.splitTextToSize(finding.description || "No description provided.", 180);
            doc.text(descLines, 14, y);
            y += descLines.length * 6 + 10;

            // Remediation
            // Check for page break
            if (y > 250) { doc.addPage(); y = 20; }
            
            doc.setFontSize(14);
            doc.setTextColor(0, 0, 0);
            doc.text("Remediation", 14, y);
            y += 7;
            doc.setFontSize(11);
            doc.setTextColor(60, 60, 60);
            const remLines = doc.splitTextToSize(finding.remediation || "No remediation provided.", 180);
            doc.text(remLines, 14, y);
            y += remLines.length * 6 + 10;

            // References
            if (finding.references && finding.references.length > 0) {
                 if (y > 250) { doc.addPage(); y = 20; }
                 doc.setFontSize(14);
                 doc.setTextColor(0, 0, 0);
                 doc.text("References", 14, y);
                 y += 7;
                 doc.setFontSize(10);
                 doc.setTextColor(0, 0, 255);
                 
                 finding.references.forEach(ref => {
                     if (y > 280) { doc.addPage(); y = 20; }
                     doc.textWithLink("• " + ref, 14, y, { url: ref });
                     y += 6;
                 });
            }
        });

        doc.save(`${report.name.replace(/\s+/g, '_')}_Report.pdf`);
        notify('success', 'Full Report exported to PDF successfully');
    } catch (e) {
        console.error(e);
        notify('error', 'Failed to export PDF');
    }
  };

  // Sort findings by severity order
  const severityOrder = {
      [Severity.CRITICAL]: 0,
      [Severity.HIGH]: 1,
      [Severity.MEDIUM]: 2,
      [Severity.LOW]: 3,
      [Severity.INFO]: 4
  };

  const sortedFindings = [...report.findings].sort((a, b) => severityOrder[a.severity] - severityOrder[b.severity]);

  return (
    <div className="p-8 h-full flex flex-col">
      {/* Header */}
      <div className="flex items-center justify-between mb-8">
        <div className="flex items-center gap-4">
            <button 
                onClick={onBack}
                className="w-10 h-10 rounded-lg bg-gray-800 hover:bg-gray-700 flex items-center justify-center text-gray-400 hover:text-white transition-all"
            >
                <i className="fa-solid fa-arrow-left"></i>
            </button>
            <div className="group cursor-pointer" onClick={() => setIsEditingReport(true)}>
                <h2 className="text-2xl font-bold text-white group-hover:text-pwn-accent transition-colors flex items-center gap-2">
                    {report.name}
                    <i className="fa-solid fa-pen text-xs opacity-0 group-hover:opacity-100 text-gray-500"></i>
                </h2>
                <div className="text-gray-400 text-sm mt-1">{report.client} • {report.date}</div>
            </div>
        </div>
        <div className="flex gap-3">
             <button 
                onClick={handleExportPDF}
                className="px-4 py-2 rounded-lg bg-gray-800 text-gray-300 hover:text-white hover:bg-gray-700 transition-all border border-gray-700 flex items-center gap-2"
             >
                <i className="fa-solid fa-file-export"></i> Export PDF
             </button>
            <button 
                onClick={handleCreateFinding}
                className="px-6 py-2 rounded-lg bg-pwn-accent text-white font-medium hover:bg-blue-600 shadow-lg shadow-blue-500/20 transition-all"
            >
                <i className="fa-solid fa-plus mr-2"></i> Add Finding
            </button>
        </div>
      </div>

      <div className="flex-1 overflow-hidden flex flex-col gap-6">
          {/* Executive Summary Section */}
          <div className="bg-pwn-panel rounded-xl border border-gray-800 overflow-hidden flex-shrink-0 shadow-lg">
             <div 
                className="p-4 bg-gray-800/50 flex justify-between items-center cursor-pointer hover:bg-gray-800 transition-colors"
                onClick={() => setSummaryExpanded(!summaryExpanded)}
             >
                 <h3 className="text-lg font-bold text-white flex items-center gap-2">
                    <i className={`fa-solid fa-chevron-${summaryExpanded ? 'down' : 'right'} text-sm text-gray-500 transition-transform`}></i>
                    Executive Summary
                 </h3>
                 <button 
                    onClick={(e) => { e.stopPropagation(); handleGenerateSummary(); }}
                    disabled={isGeneratingSummary}
                    className="text-xs bg-gradient-to-r from-purple-600 to-indigo-600 text-white px-3 py-1.5 rounded-md hover:from-purple-500 hover:to-indigo-500 transition-all flex items-center gap-2 shadow-lg shadow-purple-500/20 disabled:opacity-50 disabled:cursor-not-allowed"
                 >
                     {isGeneratingSummary ? <i className="fa-solid fa-circle-notch fa-spin"></i> : <i className="fa-solid fa-wand-magic-sparkles"></i>}
                     {report.executiveSummary ? 'Regenerate with AI' : 'Generate with AI'}
                 </button>
             </div>
             
             {summaryExpanded && (
                 <div className="p-4 border-t border-gray-800 animate-fade-in">
                    <textarea 
                        value={report.executiveSummary || ''}
                        onChange={(e) => onUpdateReport({ ...report, executiveSummary: e.target.value })}
                        className="w-full h-40 bg-pwn-dark/50 border border-gray-700 rounded-lg p-3 text-sm text-gray-300 focus:ring-1 focus:ring-pwn-accent outline-none font-mono resize-y"
                        placeholder="Click 'Generate with AI' to automatically create an executive summary based on the findings below..."
                    />
                 </div>
             )}
          </div>

          {/* Findings List */}
          <div className="flex-1 bg-pwn-panel rounded-xl border border-gray-800 overflow-hidden flex flex-col min-h-0 shadow-lg">
            <div className="p-4 border-b border-gray-800 grid grid-cols-12 text-sm font-semibold text-gray-500 uppercase tracking-wider bg-gray-800/30">
                <div className="col-span-6">Vulnerability</div>
                <div className="col-span-2">Severity</div>
                <div className="col-span-2">CVSS</div>
                <div className="col-span-2 text-right">Actions</div>
            </div>
            
            <div className="overflow-y-auto flex-1 p-2 space-y-2 custom-scrollbar">
                {sortedFindings.length === 0 ? (
                    <div className="flex flex-col items-center justify-center h-full text-gray-500 opacity-50 py-10">
                        <i className="fa-solid fa-clipboard-check text-6xl mb-4"></i>
                        <p className="text-lg">No findings added yet.</p>
                    </div>
                ) : (
                    sortedFindings.map(finding => (
                        <div 
                            key={finding.id}
                            onClick={() => handleEditFinding(finding)}
                            className="grid grid-cols-12 items-center p-4 rounded-lg hover:bg-gray-800/50 cursor-pointer transition-colors border border-transparent hover:border-gray-700 group"
                        >
                            <div className="col-span-6 pr-4">
                                <div className="font-semibold text-white group-hover:text-pwn-accent transition-colors">{finding.title}</div>
                                <div className="flex gap-2 mt-1">
                                    {finding.cveId && (
                                        <span className="text-xs bg-gray-800 text-gray-400 px-2 py-0.5 rounded border border-gray-700 inline-block">
                                            {finding.cveId}
                                        </span>
                                    )}
                                    {finding.owaspId && (
                                        <span className="text-xs bg-indigo-900/30 text-indigo-300 px-2 py-0.5 rounded border border-indigo-900/50 inline-block truncate max-w-[200px]">
                                            {finding.owaspId.split('-')[1] || finding.owaspId}
                                        </span>
                                    )}
                                </div>
                            </div>
                            <div className="col-span-2">
                                <span 
                                    className="px-3 py-1 rounded-full text-xs font-bold inline-flex items-center gap-1.5"
                                    style={{ 
                                        backgroundColor: `${SEVERITY_COLORS[finding.severity]}20`,
                                        color: SEVERITY_COLORS[finding.severity]
                                    }}
                                >
                                    <div className="w-1.5 h-1.5 rounded-full" style={{ backgroundColor: SEVERITY_COLORS[finding.severity] }}></div>
                                    {finding.severity}
                                </span>
                            </div>
                            <div className="col-span-2">
                                <div className="flex items-center gap-2">
                                    <span className={`text-sm font-mono font-bold ${
                                        finding.cvssScore >= 9 ? 'text-pwn-danger' : 
                                        finding.cvssScore >= 7 ? 'text-pwn-warning' : 'text-gray-400'
                                    }`}>
                                        {finding.cvssScore.toFixed(1)}
                                    </span>
                                    <div className="w-16 h-1.5 bg-gray-800 rounded-full overflow-hidden">
                                        <div 
                                            className="h-full rounded-full"
                                            style={{ 
                                                width: `${finding.cvssScore * 10}%`,
                                                backgroundColor: SEVERITY_COLORS[finding.severity]
                                            }}
                                        ></div>
                                    </div>
                                </div>
                            </div>
                            <div className="col-span-2 text-right">
                                <button 
                                    onClick={(e) => handleDeleteFinding(finding.id, e)}
                                    className="w-8 h-8 rounded hover:bg-red-500/20 text-gray-500 hover:text-red-500 transition-all"
                                >
                                    <i className="fa-solid fa-trash-can"></i>
                                </button>
                            </div>
                        </div>
                    ))
                )}
            </div>
          </div>
      </div>

      {editingFinding && (
        <FindingEditor 
            finding={editingFinding}
            onSave={handleSaveFinding}
            onCancel={() => setEditingFinding(null)}
            notify={notify}
            templates={templates}
        />
      )}

      {isEditingReport && (
          <ReportMetadataEditor 
            report={report}
            onSave={handleUpdateReportMetadata}
            onCancel={() => setIsEditingReport(false)}
          />
      )}
    </div>
  );
};

export default ReportDetail;